[package]
name = "reproducible"
version = "0.3.0"
edition = "2024"
description = "Utilities for reproducible accuracy and benchmark reporting in Rust projects"
license = "BSD-3-Clause"
repository = "https://github.com/p-sira/reproducible"
keywords = ["benchmark", "accuracy", "report", "testing", "reproducibility"]
categories = ["development-tools::testing", "development-tools::profiling"]

[workspace]
members = ["reproducible-macros"]

[workspace.dependencies]
reproducible-macros = { version = "0.1", path = "reproducible-macros" }

[features]
default = ["macros"]
macros = ["dep:reproducible-macros"]

[dependencies]
delegate = "0.13"
csv = "1"
getset = "0.1"
num-traits = "0.2.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tabled = "0.18"
reproducible-macros = { workspace = true, optional = true }
sysinfo = "0.38.4"

[dev-dependencies]
tempfile = "3"
criterion = "0.5"

[[bench]]
name = "latency"
harness = false
